"""Metrics, logging, and alerting observer agent.

Monitors agent activities, computes metrics, logs events to SQLite,
and triggers alerts based on configurable thresholds.
"""

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

from core.config import get_config
from core.events import Event, EventType, get_event_bus
from core.memory import get_memory

logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class Alert:
    """An alert generated by the observer."""

    id: str = ""
    severity: AlertSeverity = AlertSeverity.INFO
    source: str = ""
    message: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False

    def to_dict(self) -> Dict[str, Any]:
        """Convert alert to dictionary.

        Returns:
            Dict[str, Any]: Alert as dictionary.
        """
        return {
            "id": self.id,
            "severity": self.severity.value,
            "source": self.source,
            "message": self.message,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
            "acknowledged": self.acknowledged,
        }


class ObserverAgent:
    """Metrics, logging, and alerting agent.

    Observes all agent activities, computes metrics, logs to database,
    and triggers alerts based on configurable thresholds.

    Attributes:
        config: Application configuration.
        event_bus: Event bus for agent communication.
        memory: Persistent storage layer.
        _metrics: In-memory metrics cache.
        _alert_handlers: Registered alert handlers.
        _running: Control flag for observation loop.
    """

    def __init__(self) -> None:
        """Initialize ObserverAgent."""
        self.config = get_config()
        self.event_bus = get_event_bus()
        self._memory = None
        self._metrics: Dict[str, Any] = {
            "total_events": 0,
            "events_by_type": {},
            "events_by_agent": {},
            "task_success_rate": 0.0,
            "avg_task_duration_ms": 0,
            "error_count": 0,
            "alerts_triggered": 0,
        }
        self._alert_handlers: List[Callable[[Alert], None]] = []
        self._running = False
        self._start_time = datetime.utcnow()
        self._alert_thresholds = {
            "error_rate_threshold": 0.1,  # 10% errors triggers warning
            "task_duration_threshold_ms": 60000,  # 60s triggers warning
            "queue_depth_threshold": 100,  # 100 pending tasks triggers warning
        }
        logger.info("ObserverAgent initialized")

    async def initialize(self) -> None:
        """Initialize async components."""
        self._memory = await get_memory()
        self._running = True

        # Subscribe to all event types
        for event_type in EventType:
            self.event_bus.subscribe(event_type, self._handle_event, "observer_agent")

        logger.info("ObserverAgent async initialized")

    async def close(self) -> None:
        """Cleanup resources."""
        self._running = False
        logger.info("ObserverAgent closed")

    def _handle_event(self, event: Event) -> None:
        """Handle a received event.

        Args:
            event: The event to handle.
        """
        if not self._running:
            return

        # Run async handling in background
        asyncio.create_task(self._process_event(event))

    async def _process_event(self, event: Event) -> None:
        """Process an event and update metrics.

        Args:
            event: The event to process.
        """
        self._metrics["total_events"] += 1

        # Update type counter
        event_type = event.event_type.value
        if event_type not in self._metrics["events_by_type"]:
            self._metrics["events_by_type"][event_type] = 0
        self._metrics["events_by_type"][event_type] += 1

        # Update agent counter
        agent = event.agent or "unknown"
        if agent not in self._metrics["events_by_agent"]:
            self._metrics["events_by_agent"][agent] = 0
        self._metrics["events_by_agent"][agent] += 1

        # Log to database
        if self._memory:
            await self._memory.log_execution(
                task_id=event.task_id or "unknown",
                agent=agent,
                action=event_type,
                result="success" if event.data.get("success") else "pending",
                metadata=event.data,
            )

        # Check for error events
        if event.event_type in (EventType.TASK_FAILED, EventType.AGENT_ERROR):
            self._metrics["error_count"] += 1
            await self._check_alert_conditions(event)

        # Publish metrics updated event
        metrics_event = Event(
            event_type=EventType.METRICS_UPDATED,
            agent="observer_agent",
            data={"metrics": self._metrics},
        )
        await self.event_bus.publish(metrics_event)

    async def _check_alert_conditions(self, event: Event) -> None:
        """Check if alert conditions are met.

        Args:
            event: The triggering event.
        """
        # Check error rate
        total = self._metrics["total_events"]
        errors = self._metrics["error_count"]
        if total > 0:
            error_rate = errors / total
            if error_rate > self._alert_thresholds["error_rate_threshold"]:
                await self._trigger_alert(
                    severity=AlertSeverity.WARNING,
                    source="observer_agent",
                    message=f"Error rate {error_rate:.2%} exceeds threshold",
                    metadata={"error_rate": error_rate, "total_events": total},
                )

        # Check for specific critical errors
        if event.data.get("critical"):
            await self._trigger_alert(
                severity=AlertSeverity.CRITICAL,
                source="observer_agent",
                message=f"Critical error: {event.data.get('message', 'Unknown critical error')}",
                metadata=event.data,
            )

    async def _trigger_alert(
        self,
        severity: AlertSeverity,
        source: str,
        message: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Trigger an alert.

        Args:
            severity: Alert severity.
            source: Alert source.
            message: Alert message.
            metadata: Optional metadata.
        """
        alert = Alert(
            id=f"alert_{datetime.utcnow().timestamp()}",
            severity=severity,
            source=source,
            message=message,
            metadata=metadata or {},
        )

        self._metrics["alerts_triggered"] += 1

        logger.log(
            self._severity_to_log_level(severity),
            f"ALERT [{severity.value}] {source}: {message}",
        )

        # Publish alert event
        event = Event(
            event_type=EventType.ALERT_TRIGGERED,
            agent="observer_agent",
            data=alert.to_dict(),
        )
        await self.event_bus.publish(event)

        # Call registered handlers
        for handler in self._alert_handlers:
            try:
                handler(alert)
            except Exception as e:
                logger.error(f"Alert handler error: {e}")

    def _severity_to_log_level(self, severity: AlertSeverity) -> int:
        """Convert alert severity to logging level.

        Args:
            severity: Alert severity.

        Returns:
            int: Logging level.
        """
        mapping = {
            AlertSeverity.INFO: logging.INFO,
            AlertSeverity.WARNING: logging.WARNING,
            AlertSeverity.ERROR: logging.ERROR,
            AlertSeverity.CRITICAL: logging.CRITICAL,
        }
        return mapping.get(severity, logging.INFO)

    def register_alert_handler(self, handler: Callable[[Alert], None]) -> None:
        """Register an alert handler callback.

        Args:
            handler: Callback function to invoke when alert is triggered.
        """
        self._alert_handlers.append(handler)
        logger.debug(f"Registered alert handler: {handler.__name__}")

    def unregister_alert_handler(self, handler: Callable[[Alert], None]) -> None:
        """Unregister an alert handler.

        Args:
            handler: Handler to remove.
        """
        if handler in self._alert_handlers:
            self._alert_handlers.remove(handler)

    async def compute_metrics(self) -> Dict[str, Any]:
        """Compute current metrics snapshot.

        Returns:
            Dict[str, Any]: Current metrics.
        """
        if not self._memory:
            return self._metrics.copy()

        # Compute task metrics from database
        task_metrics = await self._memory.compute_task_metrics()

        # Compute queue status
        queue_status = await self._memory.get_queue_status()

        # Compute agent stats
        agent_stats = {}
        for agent in ["hermes_manager", "sandbox_worker", "review_agent", "observer_agent"]:
            stats = await self._memory.get_agent_stats(agent)
            if stats:
                agent_stats[agent] = stats

        # Calculate success rate
        total_tasks = sum(
            queue_status.get(status, 0)
            for status in ["completed", "failed", "in_progress"]
        )
        completed_tasks = queue_status.get("completed", 0)
        success_rate = completed_tasks / total_tasks if total_tasks > 0 else 0.0

        uptime_seconds = (datetime.utcnow() - self._start_time).total_seconds()

        return {
            **self._metrics,
            "task_metrics": task_metrics,
            "queue_status": queue_status,
            "agent_stats": agent_stats,
            "task_success_rate": success_rate,
            "uptime_seconds": uptime_seconds,
        }

    async def get_metrics_summary(self) -> str:
        """Get a human-readable metrics summary.

        Returns:
            str: Formatted metrics summary.
        """
        metrics = await self.compute_metrics()

        lines = [
            "=== Observer Agent Metrics ===",
            f"Uptime: {metrics.get('uptime_seconds', 0):.0f}s",
            f"Total Events: {metrics.get('total_events', 0)}",
            f"Error Count: {metrics.get('error_count', 0)}",
            f"Alerts Triggered: {metrics.get('alerts_triggered', 0)}",
            f"Task Success Rate: {metrics.get('task_success_rate', 0):.2%}",
            "",
            "Events by Type:",
        ]

        for event_type, count in metrics.get("events_by_type", {}).items():
            lines.append(f"  {event_type}: {count}")

        lines.append("")
        lines.append("Events by Agent:")

        for agent, count in metrics.get("events_by_agent", {}).items():
            lines.append(f"  {agent}: {count}")

        if metrics.get("queue_status"):
            lines.append("")
            lines.append("Queue Status:")
            for status, count in metrics["queue_status"].items():
                lines.append(f"  {status}: {count}")

        return "\n".join(lines)

    async def get_alerts(
        self,
        severity: Optional[AlertSeverity] = None,
        acknowledged: Optional[bool] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """Get alerts with optional filtering.

        Args:
            severity: Optional severity filter.
            acknowledged: Optional acknowledged filter.
            limit: Maximum number of results.

        Returns:
            List[Dict[str, Any]]: List of alerts.
        """
        # In production, would query from database
        # For now, return recent alerts from memory
        return []

    async def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert.

        Args:
            alert_id: Alert ID to acknowledge.

        Returns:
            bool: True if acknowledgment was successful.
        """
        logger.info(f"Acknowledging alert: {alert_id}")
        return True

    async def check_health(self) -> Dict[str, Any]:
        """Check observer agent health.

        Returns:
            Dict[str, Any]: Health status information.
        """
        uptime = (datetime.utcnow() - self._start_time).total_seconds()

        return {
            "status": "healthy",
            "uptime_seconds": uptime,
            "running": self._running,
            "total_events": self._metrics.get("total_events", 0),
            "alerts_triggered": self._metrics.get("alerts_triggered", 0),
            "registered_handlers": len(self._alert_handlers),
        }

    def set_threshold(self, key: str, value: float) -> None:
        """Set an alert threshold.

        Args:
            key: Threshold key.
            value: Threshold value.
        """
        self._alert_thresholds[key] = value
        logger.info(f"Set alert threshold {key} = {value}")

    def get_thresholds(self) -> Dict[str, float]:
        """Get current alert thresholds.

        Returns:
            Dict[str, float]: Current thresholds.
        """
        return self._alert_thresholds.copy()


# Global observer agent instance
_observer_agent: Optional[ObserverAgent] = None


async def get_observer_agent() -> ObserverAgent:
    """Get the global observer agent instance.

    Returns:
        ObserverAgent: The global observer agent instance.
    """
    global _observer_agent
    if _observer_agent is None:
        _observer_agent = ObserverAgent()
        await _observer_agent.initialize()
    return _observer_agent


async def close_observer_agent() -> None:
    """Close the global observer agent."""
    global _observer_agent
    if _observer_agent:
        await _observer_agent.close()
        _observer_agent = None